create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_green_potions integer null,
    num_green_ml integer null,
    gold integer null,
    num_red_potions integer null default 0,
    num_red_ml integer null,
    num_blue_potions integer null,
    num_blue_ml integer null,
    num_dark_potions integer null,
    num_dark_ml integer null,
    potion_capacity integer null default 50,
    ml_capacity bigint null default '10000'::bigint,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    id bigint generated by default as identity,
    price integer null default 0,
    sku text null default '""'::text,
    quantity integer null default 0,
    type integer[] null default '{}'::integer[],
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer text null default '""'::text,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    item_sku bigint null default '0'::bigint,
    quantity integer null default 0,
    cart_id bigint null,
    constraint cart_items_pkey primary key (id),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint public_cart_items_item_sku_fkey foreign key (item_sku) references potion_inventory (id)
  ) tablespace pg_default;